const NETWORKS = {
    MAINNET: 1,
    MORDENTESTNETWORK: 2,
    ROPSTENTESTNETWORK: 3,
    RINKEBYTESTNETWORK: 4,
    KOVANTESTNETWORK: 42,
    TRUFFLEDEVELOPNETWORK: 4447,
    GANACHEBLOCKCHAIN: 5777
};
Object.freeze(NETWORKS);

module.exports = NETWORKS;